<a href="https://colab.research.google.com/github/Maria-apsguiar/EstudoDeCaso-EfeitoFancy/blob/main/Investiga%C3%A7%C3%A3o_do_%22Efeito_Fancy%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#https://chiavinik.github.io/fancygeneration/$0
import pandas as pd
# vamos chamas as tabelas que queremos dar merge (mesclar)
catalago_produtos = '/content/catalogo_produtos.csv'
perfil_clientes = '//content/perfil_clientes.csv'
vendas_pedidos = '/content/vendas_pedidos.csv'

df_catalago_produtos = pd.read_csv(catalago_produtos)
df_perfil_clientes = pd.read_csv(perfil_clientes)
df_vendas_pedidos = pd.read_csv(vendas_pedidos)

#merge 3 tabelas
# primeiro fiz merge de tabela catalago_produtos com vendas_pedidos
df_catalago_produtos_vendas_pedidos = pd.merge(df_catalago_produtos, df_vendas_pedidos, left_on='sku_produto', right_on = 'sku_produto', how = 'inner')
#df_nome_tabela = pd.merge(tabela da esquerda, tabela da direita, left_on = 'nome do campo da tabela da esquerda, right_on= 'nome do campo da outra tabela)
display(df_catalago_produtos_vendas_pedidos)

,sku_produto,categoria,linha,custo_producao,preco_venda,id_pedido,id_cliente,data_compra,quantidade
0,SKU001,Chocolate,Fancy,36.19,101.34,PED000016,CLI00594,2025-05-16,2
1,SKU001,Chocolate,Fancy,36.19,101.34,PED000039,CLI01799,2025-01-26,1
2,SKU001,Chocolate,Fancy,36.19,101.34,PED000041,CLI01254,2025-10-31,1
3,SKU001,Chocolate,Fancy,36.19,101.34,PED000175,CLI05182,2025-08-07,2
4,SKU001,Chocolate,Fancy,36.19,101.34,PED000186,CLI08041,2025-08-02,1
...,...,...,...,...,...,...,...,...,...
49995,SKU050,Chocolate,Padrão,13.55,18.75,PED049892,CLI00359,2025-07-17,2
49996,SKU050,Chocolate,Padrão,13.55,18.75,PED049893,CLI04393,2025-07-31,3
49997,SKU050,Chocolate,Padrão,13.55,18.75,PED049904,CLI04199,2025-06-24,5
49998,SKU050,Chocolate,Padrão,13.55,18.75,PED049941,CLI01375,2025-12-25,5
49999,SKU050,Chocolate,Padrão,13.55,18.75,PED049976,CLI02790,2025-06-30,4

In [3]:
#merge 3 tabelas
# segundo fiz merge de tabela cdf_catalago_produtos_vendas_pedidos com perfil_clientes
df_catalago_produtos_vendas_pedidos_perfil_clientes = pd.merge(df_catalago_produtos_vendas_pedidos, df_perfil_clientes, left_on='id_cliente', right_on = 'id_cliente', how = 'inner')
#df_nome_tabela = pd.merge(tabela da esquerda, tabela da direita, left_on = 'nome do campo da tabela da esquerda, right_on= 'nome do campo da outra tabela)
display(df_catalago_produtos_vendas_pedidos_perfil_clientes)

,sku_produto,categoria,linha,custo_producao,preco_venda,id_pedido,id_cliente,data_compra,quantidade,idade,renda_mensal,estado,canal_aquisicao
0,SKU001,Chocolate,Fancy,36.19,101.34,PED000016,CLI00594,2025-05-16,2,24,4309.39,RS,Instagram
1,SKU001,Chocolate,Fancy,36.19,101.34,PED000039,CLI01799,2025-01-26,1,22,2747.79,RS,TikTok
2,SKU001,Chocolate,Fancy,36.19,101.34,PED000041,CLI01254,2025-10-31,1,25,6137.65,BA,TikTok
3,SKU001,Chocolate,Fancy,36.19,101.34,PED000175,CLI05182,2025-08-07,2,33,7120.83,BA,Instagram
4,SKU001,Chocolate,Fancy,36.19,101.34,PED000186,CLI08041,2025-08-02,1,61,5291.47,RJ,Instagram
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,SKU050,Chocolate,Padrão,13.55,18.75,PED049892,CLI00359,2025-07-17,2,44,6827.25,PR,Google
49996,SKU050,Chocolate,Padrão,13.55,18.75,PED049893,CLI04393,2025-07-31,3,24,2478.85,RS,Instagram
49997,SKU050,Chocolate,Padrão,13.55,18.75,PED049904,CLI04199,2025-06-24,5,28,5137.64,SC,Instagram
49998,SKU050,Chocolate,Padrão,13.55,18.75,PED049941,CLI01375,2025-12-25,5,64,6343.18,MG,Orgânico
49999,SKU050,Chocolate,Padrão,13.55,18.75,PED049976,CLI02790,2025-06-30,4,38,7991.57,RS,Google

In [4]:
# MARGEM DE LUCRO BRUTO
df_catalago_produtos_vendas_pedidos_perfil_clientes['Margem de Lucro Bruto'] = df_catalago_produtos_vendas_pedidos_perfil_clientes['preco_venda']-df_catalago_produtos_vendas_pedidos_perfil_clientes['custo_producao']*df_catalago_produtos_vendas_pedidos_perfil_clientes['quantidade']
df_catalago_produtos_vendas_pedidos_perfil_clientes['valor_total_do_cliente'] = df_catalago_produtos_vendas_pedidos_perfil_clientes['preco_venda']*df_catalago_produtos_vendas_pedidos_perfil_clientes['quantidade']
display(df_catalago_produtos_vendas_pedidos_perfil_clientes)

,sku_produto,categoria,linha,custo_producao,preco_venda,id_pedido,id_cliente,data_compra,quantidade,idade,renda_mensal,estado,canal_aquisicao,Margem de Lucro Bruto,valor_total_do_cliente
0,SKU001,Chocolate,Fancy,36.19,101.34,PED000016,CLI00594,2025-05-16,2,24,4309.39,RS,Instagram,28.96,202.68
1,SKU001,Chocolate,Fancy,36.19,101.34,PED000039,CLI01799,2025-01-26,1,22,2747.79,RS,TikTok,65.15,101.34
2,SKU001,Chocolate,Fancy,36.19,101.34,PED000041,CLI01254,2025-10-31,1,25,6137.65,BA,TikTok,65.15,101.34
3,SKU001,Chocolate,Fancy,36.19,101.34,PED000175,CLI05182,2025-08-07,2,33,7120.83,BA,Instagram,28.96,202.68
4,SKU001,Chocolate,Fancy,36.19,101.34,PED000186,CLI08041,2025-08-02,1,61,5291.47,RJ,Instagram,65.15,101.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,SKU050,Chocolate,Padrão,13.55,18.75,PED049892,CLI00359,2025-07-17,2,44,6827.25,PR,Google,-8.35,37.50
49996,SKU050,Chocolate,Padrão,13.55,18.75,PED049893,CLI04393,2025-07-31,3,24,2478.85,RS,Instagram,-21.90,56.25
49997,SKU050,Chocolate,Padrão,13.55,18.75,PED049904,CLI04199,2025-06-24,5,28,5137.64,SC,Instagram,-49.00,93.75
49998,SKU050,Chocolate,Padrão,13.55,18.75,PED049941,CLI01375,2025-12-25,5,64,6343.18,MG,Orgânico,-49.00,93.75
49999,SKU050,Chocolate,Padrão,13.55,18.75,PED049976,CLI02790,2025-06-30,4,38,7991.57,RS,Google,-35.45,75.00

In [5]:
# Calcular quantos itens há na coluna de quantidade e quantos há na coluna de preco_venda
# Realiza a soma de cada coluna
total_quantidade = df_catalago_produtos_vendas_pedidos_perfil_clientes['quantidade'].sum()
faturamento_total = df_catalago_produtos_vendas_pedidos_perfil_clientes['preco_venda'].sum()
ticket_medio_venda = faturamento_total / total_quantidade

# Exibe os resultados
print(f"total_quantidade: {total_quantidade}")
print(f"faturamento_total: {faturamento_total:.2f}")
print(f"Ticket Médio de vendas: R$ {ticket_medio_venda:.2f}")

total_quantidade: 139528
faturamento_total: 2224754.70
Ticket Médio de vendas: R$ 15.94

In [6]:
# para saber quantos clientes únicos
total_clientes_unicos = df_catalago_produtos_vendas_pedidos_perfil_clientes['id_cliente'].nunique()

print(f"Total de clientes únicos: {total_clientes_unicos}")

Total de clientes únicos: 9929

In [7]:
# para saber ticket médio POR Clientes
ticket_medio_por_cliente = faturamento_total / total_clientes_unicos

print(f"O Ticket Médio por cliente na base é: R$ {ticket_medio_por_cliente:.2f}")

O Ticket Médio por cliente na base é: R$ 224.07

In [8]:
#para fazer download de planilha atualizar
df_catalago_produtos_vendas_pedidos_perfil_clientes.to_csv('Dados completos.csv', index=False)